# Generated by Django 3.2.2 on 2021-07-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
